In [1]:
import pandas as pd

In [ ]:
df = pd.read_csv("Data/shopping_trends_updated.csv")
df

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3895,3896,40,Female,Hoodie,Clothing,28,Virginia,L,Turquoise,Summer,4.2,No,2-Day Shipping,No,No,32,Venmo,Weekly
3896,3897,52,Female,Backpack,Accessories,49,Iowa,L,White,Spring,4.5,No,Store Pickup,No,No,41,Bank Transfer,Bi-Weekly
3897,3898,46,Female,Belt,Accessories,33,New Jersey,L,Green,Spring,2.9,No,Standard,No,No,24,Venmo,Quarterly
3898,3899,44,Female,Shoes,Footwear,77,Minnesota,S,Brown,Summer,3.8,No,Express,No,No,24,Venmo,Weekly
3899,3900,52,Female,Handbag,Accessories,81,California,M,Beige,Spring,3.1,No,Store Pickup,No,No,33,Venmo,Quarterly

In [3]:
#1. rows and columns in dataset
print(f"rows in dataset: {df.shape[0]}")
print(f"columns in dataset: {df.shape[1]}")

rows in dataset: 3900
columns in dataset: 18

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             3900 non-null   int64
 1   Age                     3900 non-null   int64
 2   Gender                  3900 non-null   str
 3   Item Purchased          3900 non-null   str
 4   Category                3900 non-null   str
 5   Purchase Amount (USD)   3900 non-null   int64
 6   Location                3900 non-null   str
 7   Size                    3900 non-null   str
 8   Color                   3900 non-null   str
 9   Season                  3900 non-null   str
 10  Review Rating           3900 non-null   float64
 11  Subscription Status     3900 non-null   str
 12  Shipping Type           3900 non-null   str
 13  Discount Applied        3900 non-null   str
 14  Promo Code Used         3900 non-null   str
 15  Previous Purchases      3900 non-null   int64
 16  Payment Method          3900 non-null   str
 17  Frequency of Purchases  3900 non-null   str
dtypes: float64(1), int64(4), str(13)
memory usage: 835.9 KB

In [5]:
df.describe()

,Customer ID,Age,Purchase Amount (USD),Review Rating,Previous Purchases
count,3900.000000,3900.000000,3900.000000,3900.000000,3900.000000
mean,1950.500000,44.068462,59.764359,3.749949,25.351538
std,1125.977353,15.207589,23.685392,0.716223,14.447125
min,1.000000,18.000000,20.000000,2.500000,1.000000
25%,975.750000,31.000000,39.000000,3.100000,13.000000
50%,1950.500000,44.000000,60.000000,3.700000,25.000000
75%,2925.250000,57.000000,81.000000,4.400000,38.000000
max,3900.000000,70.000000,100.000000,5.000000,50.000000

In [6]:
#2. checking missing values
df.isna().sum()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Promo Code Used           0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

In [7]:
#3. total duplicate records
df.duplicated().sum()

np.int64(0)

In [8]:
#4. Categories
df.Category.unique()

<ArrowStringArray>
['Clothing', 'Footwear', 'Outerwear', 'Accessories']
Length: 4, dtype: str

In [9]:
#5. Unique Customers
df['Customer ID'].unique().sum()

np.int64(7606950)

In [10]:
#6. create age group and calculate number of customers in each group
df['Age Group'] = ['Child' if x <= 17 else 'Adult' if 17 < x <= 59 else 'Senior' for x in df['Age']]

In [11]:
df['Age Group'].value_counts()

Age Group
Adult     3112
Senior     788
Name: count, dtype: int64

In [12]:
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases,Age Group
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly,Adult
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly,Adult
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly,Adult
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly,Adult
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually,Adult

In [13]:
#7. Top 10 most purchased item
df['Item Purchased'].value_counts().sort_values(ascending=False)[:10]

Item Purchased
Blouse        171
Pants         171
Jewelry       171
Shirt         169
Dress         166
Sweater       164
Jacket        163
Coat          161
Sunglasses    161
Belt          161
Name: count, dtype: int64

In [14]:
#8. total and average purchase amount by category
df2 = df.groupby('Category').agg({'Purchase Amount (USD)':['sum','mean']}).reset_index()

In [15]:
#9. average purchase amount of subscribed and non subscribed customers
df.groupby('Subscription Status')['Purchase Amount (USD)'].mean()

Subscription Status
No     59.865121
Yes    59.491928
Name: Purchase Amount (USD), dtype: float64

In [16]:
#10. Payment menthod for each customer gender
pd.crosstab(df['Gender'],df['Payment Method'])

Payment Method  Bank Transfer  Cash  Credit Card  Debit Card  PayPal  Venmo
Gender
Female                    203   212          223         181     221    208
Male                      409   458          448         455     456    426

In [17]:
#11. customer groups by location and category based on total purchase amount
df.groupby(['Location','Category'])['Purchase Amount (USD)'].sum()

Location   Category
Alabama    Accessories    1576
           Clothing       2334
           Footwear        914
           Outerwear       437
Alaska     Accessories    1719
                          ...
Wisconsin  Outerwear       120
Wyoming    Accessories    1388
           Clothing       1850
           Footwear        703
           Outerwear       368
Name: Purchase Amount (USD), Length: 200, dtype: int64

In [18]:
#12. customer segment and their revenue
df.groupby('Subscription Status')['Purchase Amount (USD)'].sum()

Subscription Status
No     170436
Yes     62645
Name: Purchase Amount (USD), dtype: int64

In [27]:
#13. categories with high purchase volume and low average purchase amount
categories = df.groupby('Category').agg({'Purchase Amount (USD)':['count','mean']}).reset_index()
categories

      Category Purchase Amount (USD)
                               count       mean
0  Accessories                  1240  59.838710
1     Clothing                  1737  60.025331
2     Footwear                   599  60.255426
3    Outerwear                   324  57.172840

In [28]:
categories.sort_values([('Purchase Amount (USD)','count'),('Purchase Amount (USD)','mean')],ascending=[False,True])

      Category Purchase Amount (USD)
                               count       mean
1     Clothing                  1737  60.025331
0  Accessories                  1240  59.838710
2     Footwear                   599  60.255426
3    Outerwear                   324  57.172840

In [37]:
#14. item purchased with strong average rating and low purchased volume
df2 = df.groupby('Item Purchased').agg({'Review Rating':'mean','Purchase Amount (USD)':'count'}).reset_index()

In [38]:
df2.rename(columns={'Purchase Amount (USD)':'Purchase Volume'},inplace=True)

In [40]:
df2.sort_values(by=['Review Rating','Purchase Volume'],ascending=[False,True])

   Item Purchased  Review Rating  Purchase Volume
6          Gloves       3.864286              140
14        Sandals       3.841250              160
3           Boots       3.812500              144
8             Hat       3.806494              154
24        T-shirt       3.782993              147
19          Skirt       3.782278              158
7         Handbag       3.775163              153
23        Sweater       3.767073              164
10         Jacket       3.763190              163
1            Belt       3.761491              161
20       Sneakers       3.757931              145
12        Jewelry       3.756140              171
5           Dress       3.754819              166
0        Backpack       3.752448              143
21          Socks       3.750943              159
17          Shoes       3.747333              150
22     Sunglasses       3.744720              161
4            Coat       3.730435              161
9          Hoodie       3.719205              151
13          Pants       3.718713              171
18         Shorts       3.711465              157
15          Scarf       3.700000              157
2          Blouse       3.683626              171
11          Jeans       3.648387              124
16          Shirt       3.629586              169

Index(['Customer ID', 'Age', 'Gender', 'Item Purchased', 'Category',
       'Purchase Amount (USD)', 'Location', 'Size', 'Color', 'Season',
       'Review Rating', 'Subscription Status', 'Shipping Type',
       'Discount Applied', 'Promo Code Used', 'Previous Purchases',
       'Payment Method', 'Frequency of Purchases', 'Age Group'],
      dtype='str')